name: Tests

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          stable: "false"
          go-version: "1.15.4"
      - name: Run Linters
        run: ./.github/run_linters.sh
      - name: Run Tests
        run: go test -v
